name: Zip Directories and Upload to Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - main

jobs:


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install 7-Zip
        run: sudo apt-get update && sudo apt-get install p7zip-full

      - name: Zip Directories
        run: |
          for d in */ ; do
            7z a -tzip "${d%/}.zip" "$d"
          done

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: ./*.zip
